train:
  batch_size_per_gpu: 20
  dataset_path: "COCO_stuff_164K" 
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_large
  patch_size: 14
  num_points: 200
  num_classes: 171
  pretrained_weights: './dinov2_vitl14_pretrain.pth'
optim:
  epochs: 22
  warmup_epochs: 1
  lr: 1e-2 
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 27400 