train:
  batch_size_per_gpu: 12
  dataset_path: "Cityscapes"
  OFFICIAL_EPOCH_LENGTH: 575
student:
  arch: vit_large
  patch_size: 14
  num_points: 100
  num_classes: 19
  pretrained_weights: './dinov2_vitl14_pretrain.pth'
optim:
  epochs: 50
  # warmup_epochs: 1
  warmup_epochs: 0
  lr: 3e-3
crops:
  global_crops_size: [518, 1036]
evaluation:
  eval_period_iterations: 28700