train:
  batch_size_per_gpu: 20
  # num_workers: 1
  dataset_path: "COCO" 
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_base
  patch_size: 14
  num_points: 150
  num_classes: 133
  pretrained_weights: './dinov2_vitb14_pretrain.pth'
  # drop_path_rate: 0.4
  # ffn_layer: swiglufused
  # block_chunks: 4
optim:
  epochs: 20
  warmup_epochs: 1
  lr: 1e-2 
crops:
  global_crops_size: [518, 518]
  # global_crops_size: 518
