train:
  # batch_size_per_gpu: 32
  batch_size_per_gpu: 20
  dataset_path: "ADE20k"
  OFFICIAL_EPOCH_LENGTH: 320
student:
  arch: vit_base
  patch_size: 14
  num_points: 250
  num_classes: 150
  pretrained_weights: './dinov2_vitb14_pretrain.pth'
  # pretrained_weights: './checkpoint.pth'
  # drop_path_rate: 0.4
  # ffn_layer: swiglufused
  # block_chunks: 4
optim:
  epochs: 40
  warmup_epochs: 1
  lr: 3e-3
crops:
  global_crops_size: [518, 518]