train:
  # batch_size_per_gpu: 20
  batch_size_per_gpu: 10
  dataset_path: "Cityscapes"
  # OFFICIAL_EPOCH_LENGTH: 63
  OFFICIAL_EPOCH_LENGTH: 125
student:
  arch: vit_large
  patch_size: 14
  num_points: 250
  num_classes: 19
  # pretrained_weights: './checkpoint.pth'
  pretrained_weights: './dinov2_vitl14_pretrain.pth'
  # drop_path_rate: 0.4
  # ffn_layer: swiglufused
  # block_chunks: 4
optim:
  epochs: 40
  warmup_epochs: 1
  lr: 1e-2
crops:
  global_crops_size: [518, 1036]
evaluation:
  # eval_period_iterations: 315 
  eval_period_iterations: 625