train:
  batch_size_per_gpu: 70
  dataset_path: "Objects365"
  OFFICIAL_EPOCH_LENGTH: 6222
  cache_dataset: false
student:
  arch: vit_base
  patch_size: 14
  num_points: 250
  num_classes: 365
  pretrained_weights: './dinov2_vitb14_pretrain.pth'
optim:
  epochs: 3
  warmup_epochs: 0
  lr: 1e-2
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 6222
