train:
  batch_size_per_gpu: 20
  dataset_path: "Cityscapes"
  OFFICIAL_EPOCH_LENGTH: 345
student:
  arch: vit_base
  patch_size: 14
  num_points: 250
  num_classes: 19
  # pretrained_weights: './checkpoint.pth'
  pretrained_weights: './dinov2_vitb14_pretrain.pth'
optim:
  epochs: 60
  # warmup_epochs: 1
  warmup_epochs: 0
  lr: 1e-2
crops:
  global_crops_size: [518, 1036]
evaluation:
  eval_period_iterations: 12000