train:
  batch_size_per_gpu: 20
  dataset_path: "COCO" 
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_base
  patch_size: 14
  num_points: 150
  num_classes: 133
  pretrained_weights: './dinov2_vitb14_pretrain.pth'
  #pretrained_weights: './checkpoint.pth'
optim:
  epochs: 30
  # warmup_epochs: 1
  warmup_epochs: 0
  lr: 6e-3
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 34900 
