train:
  batch_size_per_gpu: 20
  # num_workers: 1
  dataset_path: "COCO" 
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_large
  patch_size: 14
  num_points: 250
  num_classes: 133
  pretrained_weights: './checkpoint.pth'
optim:
  epochs: 30
  warmup_epochs: 0
  lr: 1e-2 
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 18700