train:
  batch_size_per_gpu: 20
  dataset_path: "Objects365"
  OFFICIAL_EPOCH_LENGTH: 2177
student:
  arch: vit_large
  patch_size: 14
  num_points: 250
  num_classes: 365
optim:
  epochs: 5
  warmup_epochs: 1
  lr: 1e-2
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 4354