train:
  batch_size_per_gpu: 20
  dataset_path: "ADE20k"
  OFFICIAL_EPOCH_LENGTH: 320
student:
  arch: vit_large
  patch_size: 14
  num_points: 200
  num_classes: 150
  pretrained_weights: './dinov2_vitl14_pretrain.pth'
optim:
  epochs: 60
  warmup_epochs: 250
  lr: 3e-2
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 19100